### ISSUE TITLE
Crash in XYChart

### ISSUE THREAD

**Issue by naixx** [KoalaPlot/koalaplot-core#92]
```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at io.github.koalaplot.core.xygraph.ChartAreas.xTickSpacing(XYGraph.kt:305)
       at io.github.koalaplot.core.xygraph.ChartAreas.withComputedXAxisLabelAreas(XYGraph.kt:338)
       at io.github.koalaplot.core.xygraph.XYGraphKt.optimizeGraphSize-m8Kt_7k(XYGraph.kt:455)
       at io.github.koalaplot.core.xygraph.XYGraphKt.access$optimizeGraphSize-m8Kt_7k(XYGraph.kt:1)
       at io.github.koalaplot.core.xygraph.XYAxisMeasurePolicy.measure-3p2s80s(XYGraph.kt:471)
       at io.github.koalaplot.core.xygraph.XYGraphKt$XYGraph$1.invoke$lambda$1(XYGraph.kt:169)
       at io.github.koalaplot.core.xygraph.XYGraphKt$XYGraph$1.$r8$lambda$iw5cUcwWxr4LkRSreFAcyqGwEpg()
       at io.github.koalaplot.core.xygraph.XYGraphKt$XYGraph$1$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:725)
```
Long story short, I got a stacktrace from crashlytics. Unfortunately I can't even name which graph is that or reproduce in a stable manner because there are several chart types on the screen. I assume that there is some problem with ticks or legend? Probably it can be good to have validation on initializing, not rendering

**Comment by gsteckman** [comment]
This is occurring because there are no major ticks on the x-axis. Regardless, I added guards to avoid division by 0 in several places which is now in release 0.6.4. Without any ticks there won't be any labels to indicate values to the user, so there is something going on with the size of the plot and/or axis settings like ```minimumMajorTIckSpacing``` you might want to check into.
